package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresses generated by hbm2java
 */
@Entity
@Table(name = "adresses", catalog = "dbprojet")
public class Adresses implements java.io.Serializable {

	private int idAdresse;
	private Integer numero;
	private String nomVoie;
	private String codePostal;
	private String ville;
	private Set reparateurses = new HashSet(0);
	private Set clientsesForIdAdresse2 = new HashSet(0);
	private Set clientsesForIdAdresse = new HashSet(0);
	private Set vendeurses = new HashSet(0);

	public Adresses() {
	}

	public Adresses(int idAdresse) {
		this.idAdresse = idAdresse;
	}

	public Adresses(int idAdresse, Integer numero, String nomVoie,
			String codePostal, String ville, Set reparateurses,
			Set clientsesForIdAdresse2, Set clientsesForIdAdresse,
			Set vendeurses) {
		this.idAdresse = idAdresse;
		this.numero = numero;
		this.nomVoie = nomVoie;
		this.codePostal = codePostal;
		this.ville = ville;
		this.reparateurses = reparateurses;
		this.clientsesForIdAdresse2 = clientsesForIdAdresse2;
		this.clientsesForIdAdresse = clientsesForIdAdresse;
		this.vendeurses = vendeurses;
	}

	@Id
	@Column(name = "id_adresse", unique = true, nullable = false)
	public int getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(int idAdresse) {
		this.idAdresse = idAdresse;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "nom_voie", length = 45)
	public String getNomVoie() {
		return this.nomVoie;
	}

	public void setNomVoie(String nomVoie) {
		this.nomVoie = nomVoie;
	}

	@Column(name = "code_postal", length = 45)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "ville", length = 45)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresses")
	public Set getReparateurses() {
		return this.reparateurses;
	}

	public void setReparateurses(Set reparateurses) {
		this.reparateurses = reparateurses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adressesByIdAdresse2")
	public Set getClientsesForIdAdresse2() {
		return this.clientsesForIdAdresse2;
	}

	public void setClientsesForIdAdresse2(Set clientsesForIdAdresse2) {
		this.clientsesForIdAdresse2 = clientsesForIdAdresse2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adressesByIdAdresse")
	public Set getClientsesForIdAdresse() {
		return this.clientsesForIdAdresse;
	}

	public void setClientsesForIdAdresse(Set clientsesForIdAdresse) {
		this.clientsesForIdAdresse = clientsesForIdAdresse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresses")
	public Set getVendeurses() {
		return this.vendeurses;
	}

	public void setVendeurses(Set vendeurses) {
		this.vendeurses = vendeurses;
	}

}
