package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name = "clients", catalog = "dbprojet")
public class Clients implements java.io.Serializable {

	private int idClient;
	private Adresses adressesByIdAdresse2;
	private Adresses adressesByIdAdresse;
	private Comptes comptes;
	private String nom;
	private String prenom;
	private String mail;
	private Set cltProdGarVends = new HashSet(0);

	public Clients() {
	}

	public Clients(int idClient) {
		this.idClient = idClient;
	}

	public Clients(int idClient, Adresses adressesByIdAdresse2,
			Adresses adressesByIdAdresse, Comptes comptes, String nom,
			String prenom, String mail, Set cltProdGarVends) {
		this.idClient = idClient;
		this.adressesByIdAdresse2 = adressesByIdAdresse2;
		this.adressesByIdAdresse = adressesByIdAdresse;
		this.comptes = comptes;
		this.nom = nom;
		this.prenom = prenom;
		this.mail = mail;
		this.cltProdGarVends = cltProdGarVends;
	}

	@Id
	@Column(name = "id_client", unique = true, nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_adresse2")
	public Adresses getAdressesByIdAdresse2() {
		return this.adressesByIdAdresse2;
	}

	public void setAdressesByIdAdresse2(Adresses adressesByIdAdresse2) {
		this.adressesByIdAdresse2 = adressesByIdAdresse2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_adresse")
	public Adresses getAdressesByIdAdresse() {
		return this.adressesByIdAdresse;
	}

	public void setAdressesByIdAdresse(Adresses adressesByIdAdresse) {
		this.adressesByIdAdresse = adressesByIdAdresse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_compte")
	public Comptes getComptes() {
		return this.comptes;
	}

	public void setComptes(Comptes comptes) {
		this.comptes = comptes;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "mail", length = 254)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set getCltProdGarVends() {
		return this.cltProdGarVends;
	}

	public void setCltProdGarVends(Set cltProdGarVends) {
		this.cltProdGarVends = cltProdGarVends;
	}

}
