package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CltProdGarVendId generated by hbm2java
 */
@Embeddable
public class CltProdGarVendId implements java.io.Serializable {

	private int idClient;
	private int idProduit;
	private Integer idGarantie;
	private Integer idVendeur;
	private Integer idReparation;
	private Date dateAchat;

	public CltProdGarVendId() {
	}

	public CltProdGarVendId(int idClient, int idProduit, Date dateAchat) {
		this.idClient = idClient;
		this.idProduit = idProduit;
		this.dateAchat = dateAchat;
	}

	public CltProdGarVendId(int idClient, int idProduit, Integer idGarantie,
			Integer idVendeur, Integer idReparation, Date dateAchat) {
		this.idClient = idClient;
		this.idProduit = idProduit;
		this.idGarantie = idGarantie;
		this.idVendeur = idVendeur;
		this.idReparation = idReparation;
		this.dateAchat = dateAchat;
	}

	@Column(name = "id_client", nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "id_produit", nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "id_garantie")
	public Integer getIdGarantie() {
		return this.idGarantie;
	}

	public void setIdGarantie(Integer idGarantie) {
		this.idGarantie = idGarantie;
	}

	@Column(name = "id_vendeur")
	public Integer getIdVendeur() {
		return this.idVendeur;
	}

	public void setIdVendeur(Integer idVendeur) {
		this.idVendeur = idVendeur;
	}

	@Column(name = "id_reparation")
	public Integer getIdReparation() {
		return this.idReparation;
	}

	public void setIdReparation(Integer idReparation) {
		this.idReparation = idReparation;
	}

	@Column(name = "date_achat", nullable = false, length = 10)
	public Date getDateAchat() {
		return this.dateAchat;
	}

	public void setDateAchat(Date dateAchat) {
		this.dateAchat = dateAchat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CltProdGarVendId))
			return false;
		CltProdGarVendId castOther = (CltProdGarVendId) other;

		return (this.getIdClient() == castOther.getIdClient())
				&& (this.getIdProduit() == castOther.getIdProduit())
				&& ((this.getIdGarantie() == castOther.getIdGarantie()) || (this
						.getIdGarantie() != null
						&& castOther.getIdGarantie() != null && this
						.getIdGarantie().equals(castOther.getIdGarantie())))
				&& ((this.getIdVendeur() == castOther.getIdVendeur()) || (this
						.getIdVendeur() != null
						&& castOther.getIdVendeur() != null && this
						.getIdVendeur().equals(castOther.getIdVendeur())))
				&& ((this.getIdReparation() == castOther.getIdReparation()) || (this
						.getIdReparation() != null
						&& castOther.getIdReparation() != null && this
						.getIdReparation().equals(castOther.getIdReparation())))
				&& ((this.getDateAchat() == castOther.getDateAchat()) || (this
						.getDateAchat() != null
						&& castOther.getDateAchat() != null && this
						.getDateAchat().equals(castOther.getDateAchat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdClient();
		result = 37 * result + this.getIdProduit();
		result = 37
				* result
				+ (getIdGarantie() == null ? 0 : this.getIdGarantie()
						.hashCode());
		result = 37 * result
				+ (getIdVendeur() == null ? 0 : this.getIdVendeur().hashCode());
		result = 37
				* result
				+ (getIdReparation() == null ? 0 : this.getIdReparation()
						.hashCode());
		result = 37 * result
				+ (getDateAchat() == null ? 0 : this.getDateAchat().hashCode());
		return result;
	}

}
