package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CltProdGarVend generated by hbm2java
 */
@Entity
@Table(name = "clt_prod_gar_vend", catalog = "dbprojet")
public class CltProdGarVend implements java.io.Serializable {

	private CltProdGarVendId id;
	private Vendeurs vendeurs;
	private Reparations reparations;
	private Produits produits;
	private Garanties garanties;
	private Clients clients;

	public CltProdGarVend() {
	}

	public CltProdGarVend(CltProdGarVendId id, Produits produits,
			Clients clients) {
		this.id = id;
		this.produits = produits;
		this.clients = clients;
	}

	public CltProdGarVend(CltProdGarVendId id, Vendeurs vendeurs,
			Reparations reparations, Produits produits, Garanties garanties,
			Clients clients) {
		this.id = id;
		this.vendeurs = vendeurs;
		this.reparations = reparations;
		this.produits = produits;
		this.garanties = garanties;
		this.clients = clients;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idClient", column = @Column(name = "id_client", nullable = false)),
			@AttributeOverride(name = "idProduit", column = @Column(name = "id_produit", nullable = false)),
			@AttributeOverride(name = "idGarantie", column = @Column(name = "id_garantie")),
			@AttributeOverride(name = "idVendeur", column = @Column(name = "id_vendeur")),
			@AttributeOverride(name = "idReparation", column = @Column(name = "id_reparation")),
			@AttributeOverride(name = "dateAchat", column = @Column(name = "date_achat", nullable = false, length = 10)) })
	public CltProdGarVendId getId() {
		return this.id;
	}

	public void setId(CltProdGarVendId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_vendeur", insertable = false, updatable = false)
	public Vendeurs getVendeurs() {
		return this.vendeurs;
	}

	public void setVendeurs(Vendeurs vendeurs) {
		this.vendeurs = vendeurs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reparation", insertable = false, updatable = false)
	public Reparations getReparations() {
		return this.reparations;
	}

	public void setReparations(Reparations reparations) {
		this.reparations = reparations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produit", nullable = false, insertable = false, updatable = false)
	public Produits getProduits() {
		return this.produits;
	}

	public void setProduits(Produits produits) {
		this.produits = produits;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_garantie", insertable = false, updatable = false)
	public Garanties getGaranties() {
		return this.garanties;
	}

	public void setGaranties(Garanties garanties) {
		this.garanties = garanties;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_client", nullable = false, insertable = false, updatable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

}
