package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comptes generated by hbm2java
 */
@Entity
@Table(name = "comptes", catalog = "dbprojet")
public class Comptes implements java.io.Serializable {

	private int idCompte;
	private String login;
	private String pwd;
	private Integer type;
	private Set vendeurses = new HashSet(0);
	private Set clientses = new HashSet(0);
	private Set reparateurses = new HashSet(0);

	public Comptes() {
	}

	public Comptes(int idCompte) {
		this.idCompte = idCompte;
	}

	public Comptes(int idCompte, String login, String pwd, Integer type,
			Set vendeurses, Set clientses, Set reparateurses) {
		this.idCompte = idCompte;
		this.login = login;
		this.pwd = pwd;
		this.type = type;
		this.vendeurses = vendeurses;
		this.clientses = clientses;
		this.reparateurses = reparateurses;
	}

	@Id
	@Column(name = "id_compte", unique = true, nullable = false)
	public int getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(int idCompte) {
		this.idCompte = idCompte;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "pwd", length = 254)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comptes")
	public Set getVendeurses() {
		return this.vendeurses;
	}

	public void setVendeurses(Set vendeurses) {
		this.vendeurses = vendeurses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comptes")
	public Set getClientses() {
		return this.clientses;
	}

	public void setClientses(Set clientses) {
		this.clientses = clientses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comptes")
	public Set getReparateurses() {
		return this.reparateurses;
	}

	public void setReparateurses(Set reparateurses) {
		this.reparateurses = reparateurses;
	}

}
