package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Garanties generated by hbm2java
 */
@Entity
@Table(name = "garanties", catalog = "dbprojet")
public class Garanties implements java.io.Serializable {

	private int idGarantie;
	private Integer duree;
	private Float cout;
	private Set prodGars = new HashSet(0);
	private Set cltProdGarVends = new HashSet(0);
	private Set vendGars = new HashSet(0);

	public Garanties() {
	}

	public Garanties(int idGarantie) {
		this.idGarantie = idGarantie;
	}

	public Garanties(int idGarantie, Integer duree, Float cout, Set prodGars,
			Set cltProdGarVends, Set vendGars) {
		this.idGarantie = idGarantie;
		this.duree = duree;
		this.cout = cout;
		this.prodGars = prodGars;
		this.cltProdGarVends = cltProdGarVends;
		this.vendGars = vendGars;
	}

	@Id
	@Column(name = "id_garantie", unique = true, nullable = false)
	public int getIdGarantie() {
		return this.idGarantie;
	}

	public void setIdGarantie(int idGarantie) {
		this.idGarantie = idGarantie;
	}

	@Column(name = "duree")
	public Integer getDuree() {
		return this.duree;
	}

	public void setDuree(Integer duree) {
		this.duree = duree;
	}

	@Column(name = "cout", precision = 12, scale = 0)
	public Float getCout() {
		return this.cout;
	}

	public void setCout(Float cout) {
		this.cout = cout;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garanties")
	public Set getProdGars() {
		return this.prodGars;
	}

	public void setProdGars(Set prodGars) {
		this.prodGars = prodGars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garanties")
	public Set getCltProdGarVends() {
		return this.cltProdGarVends;
	}

	public void setCltProdGarVends(Set cltProdGarVends) {
		this.cltProdGarVends = cltProdGarVends;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garanties")
	public Set getVendGars() {
		return this.vendGars;
	}

	public void setVendGars(Set vendGars) {
		this.vendGars = vendGars;
	}

}
