package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pannes generated by hbm2java
 */
@Entity
@Table(name = "pannes", catalog = "dbprojet")
public class Pannes implements java.io.Serializable {

	private int idPanne;
	private String nom;
	private String forfait;
	private Float cout;
	private Set prodPannes = new HashSet(0);
	private Set reparationses = new HashSet(0);

	public Pannes() {
	}

	public Pannes(int idPanne) {
		this.idPanne = idPanne;
	}

	public Pannes(int idPanne, String nom, String forfait, Float cout,
			Set prodPannes, Set reparationses) {
		this.idPanne = idPanne;
		this.nom = nom;
		this.forfait = forfait;
		this.cout = cout;
		this.prodPannes = prodPannes;
		this.reparationses = reparationses;
	}

	@Id
	@Column(name = "id_panne", unique = true, nullable = false)
	public int getIdPanne() {
		return this.idPanne;
	}

	public void setIdPanne(int idPanne) {
		this.idPanne = idPanne;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "forfait", length = 254)
	public String getForfait() {
		return this.forfait;
	}

	public void setForfait(String forfait) {
		this.forfait = forfait;
	}

	@Column(name = "cout", precision = 12, scale = 0)
	public Float getCout() {
		return this.cout;
	}

	public void setCout(Float cout) {
		this.cout = cout;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pannes")
	public Set getProdPannes() {
		return this.prodPannes;
	}

	public void setProdPannes(Set prodPannes) {
		this.prodPannes = prodPannes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pannes")
	public Set getReparationses() {
		return this.reparationses;
	}

	public void setReparationses(Set reparationses) {
		this.reparationses = reparationses;
	}

}
