package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdGarId generated by hbm2java
 */
@Embeddable
public class ProdGarId implements java.io.Serializable {

	private int idProduit;
	private int idGarantie;

	public ProdGarId() {
	}

	public ProdGarId(int idProduit, int idGarantie) {
		this.idProduit = idProduit;
		this.idGarantie = idGarantie;
	}

	@Column(name = "id_produit", nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "id_garantie", nullable = false)
	public int getIdGarantie() {
		return this.idGarantie;
	}

	public void setIdGarantie(int idGarantie) {
		this.idGarantie = idGarantie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdGarId))
			return false;
		ProdGarId castOther = (ProdGarId) other;

		return (this.getIdProduit() == castOther.getIdProduit())
				&& (this.getIdGarantie() == castOther.getIdGarantie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduit();
		result = 37 * result + this.getIdGarantie();
		return result;
	}

}
