package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdGar generated by hbm2java
 */
@Entity
@Table(name = "prod_gar", catalog = "dbprojet")
public class ProdGar implements java.io.Serializable {

	private ProdGarId id;
	private Produits produits;
	private Garanties garanties;

	public ProdGar() {
	}

	public ProdGar(ProdGarId id, Produits produits, Garanties garanties) {
		this.id = id;
		this.produits = produits;
		this.garanties = garanties;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProduit", column = @Column(name = "id_produit", nullable = false)),
			@AttributeOverride(name = "idGarantie", column = @Column(name = "id_garantie", nullable = false)) })
	public ProdGarId getId() {
		return this.id;
	}

	public void setId(ProdGarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produit", nullable = false, insertable = false, updatable = false)
	public Produits getProduits() {
		return this.produits;
	}

	public void setProduits(Produits produits) {
		this.produits = produits;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_garantie", nullable = false, insertable = false, updatable = false)
	public Garanties getGaranties() {
		return this.garanties;
	}

	public void setGaranties(Garanties garanties) {
		this.garanties = garanties;
	}

}
