package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdPanne generated by hbm2java
 */
@Entity
@Table(name = "prod_panne", catalog = "dbprojet")
public class ProdPanne implements java.io.Serializable {

	private ProdPanneId id;
	private Pannes pannes;
	private Produits produits;

	public ProdPanne() {
	}

	public ProdPanne(ProdPanneId id, Pannes pannes, Produits produits) {
		this.id = id;
		this.pannes = pannes;
		this.produits = produits;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProduit", column = @Column(name = "id_produit", nullable = false)),
			@AttributeOverride(name = "idPanne", column = @Column(name = "id_panne", nullable = false)) })
	public ProdPanneId getId() {
		return this.id;
	}

	public void setId(ProdPanneId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_panne", nullable = false, insertable = false, updatable = false)
	public Pannes getPannes() {
		return this.pannes;
	}

	public void setPannes(Pannes pannes) {
		this.pannes = pannes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produit", nullable = false, insertable = false, updatable = false)
	public Produits getProduits() {
		return this.produits;
	}

	public void setProduits(Produits produits) {
		this.produits = produits;
	}

}
