package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdPanneId generated by hbm2java
 */
@Embeddable
public class ProdPanneId implements java.io.Serializable {

	private int idProduit;
	private int idPanne;

	public ProdPanneId() {
	}

	public ProdPanneId(int idProduit, int idPanne) {
		this.idProduit = idProduit;
		this.idPanne = idPanne;
	}

	@Column(name = "id_produit", nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "id_panne", nullable = false)
	public int getIdPanne() {
		return this.idPanne;
	}

	public void setIdPanne(int idPanne) {
		this.idPanne = idPanne;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdPanneId))
			return false;
		ProdPanneId castOther = (ProdPanneId) other;

		return (this.getIdProduit() == castOther.getIdProduit())
				&& (this.getIdPanne() == castOther.getIdPanne());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduit();
		result = 37 * result + this.getIdPanne();
		return result;
	}

}
