package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produits generated by hbm2java
 */
@Entity
@Table(name = "produits", catalog = "dbprojet")
public class Produits implements java.io.Serializable {

	private int idProduit;
	private String categorie;
	private String marque;
	private String modele;
	private String urlImg;
	private Integer transportable;
	private Integer garantieConstructeur;
	private Integer garantieIncluse;
	private Set prodGars = new HashSet(0);
	private Set prodPannes = new HashSet(0);
	private Set cltProdGarVends = new HashSet(0);

	public Produits() {
	}

	public Produits(int idProduit) {
		this.idProduit = idProduit;
	}

	public Produits(int idProduit, String categorie, String marque,
			String modele, String urlImg, Integer transportable,
			Integer garantieConstructeur, Integer garantieIncluse,
			Set prodGars, Set prodPannes, Set cltProdGarVends) {
		this.idProduit = idProduit;
		this.categorie = categorie;
		this.marque = marque;
		this.modele = modele;
		this.urlImg = urlImg;
		this.transportable = transportable;
		this.garantieConstructeur = garantieConstructeur;
		this.garantieIncluse = garantieIncluse;
		this.prodGars = prodGars;
		this.prodPannes = prodPannes;
		this.cltProdGarVends = cltProdGarVends;
	}

	@Id
	@Column(name = "id_produit", unique = true, nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "categorie", length = 254)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Column(name = "marque", length = 254)
	public String getMarque() {
		return this.marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	@Column(name = "modele", length = 254)
	public String getModele() {
		return this.modele;
	}

	public void setModele(String modele) {
		this.modele = modele;
	}

	@Column(name = "urlImg", length = 254)
	public String getUrlImg() {
		return this.urlImg;
	}

	public void setUrlImg(String urlImg) {
		this.urlImg = urlImg;
	}

	@Column(name = "transportable")
	public Integer getTransportable() {
		return this.transportable;
	}

	public void setTransportable(Integer transportable) {
		this.transportable = transportable;
	}

	@Column(name = "garantieConstructeur")
	public Integer getGarantieConstructeur() {
		return this.garantieConstructeur;
	}

	public void setGarantieConstructeur(Integer garantieConstructeur) {
		this.garantieConstructeur = garantieConstructeur;
	}

	@Column(name = "garantieIncluse")
	public Integer getGarantieIncluse() {
		return this.garantieIncluse;
	}

	public void setGarantieIncluse(Integer garantieIncluse) {
		this.garantieIncluse = garantieIncluse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produits")
	public Set getProdGars() {
		return this.prodGars;
	}

	public void setProdGars(Set prodGars) {
		this.prodGars = prodGars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produits")
	public Set getProdPannes() {
		return this.prodPannes;
	}

	public void setProdPannes(Set prodPannes) {
		this.prodPannes = prodPannes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produits")
	public Set getCltProdGarVends() {
		return this.cltProdGarVends;
	}

	public void setCltProdGarVends(Set cltProdGarVends) {
		this.cltProdGarVends = cltProdGarVends;
	}

}
