package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reparateurs generated by hbm2java
 */
@Entity
@Table(name = "reparateurs", catalog = "dbprojet")
public class Reparateurs implements java.io.Serializable {

	private int idReparateur;
	private Adresses adresses;
	private Comptes comptes;
	private String nom;
	private Integer nbReparation;
	private String mail;
	private Set reparationses = new HashSet(0);

	public Reparateurs() {
	}

	public Reparateurs(int idReparateur) {
		this.idReparateur = idReparateur;
	}

	public Reparateurs(int idReparateur, Adresses adresses, Comptes comptes,
			String nom, Integer nbReparation, String mail, Set reparationses) {
		this.idReparateur = idReparateur;
		this.adresses = adresses;
		this.comptes = comptes;
		this.nom = nom;
		this.nbReparation = nbReparation;
		this.mail = mail;
		this.reparationses = reparationses;
	}

	@Id
	@Column(name = "id_reparateur", unique = true, nullable = false)
	public int getIdReparateur() {
		return this.idReparateur;
	}

	public void setIdReparateur(int idReparateur) {
		this.idReparateur = idReparateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_adresse")
	public Adresses getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Adresses adresses) {
		this.adresses = adresses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_compte")
	public Comptes getComptes() {
		return this.comptes;
	}

	public void setComptes(Comptes comptes) {
		this.comptes = comptes;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "nb_reparation")
	public Integer getNbReparation() {
		return this.nbReparation;
	}

	public void setNbReparation(Integer nbReparation) {
		this.nbReparation = nbReparation;
	}

	@Column(name = "mail", length = 254)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reparateurs")
	public Set getReparationses() {
		return this.reparationses;
	}

	public void setReparationses(Set reparationses) {
		this.reparationses = reparationses;
	}

}
