package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reparations generated by hbm2java
 */
@Entity
@Table(name = "reparations", catalog = "dbprojet")
public class Reparations implements java.io.Serializable {

	private int idReparation;
	private Pannes pannes;
	private Reparateurs reparateurs;
	private String description;
	private Date dateEtat;
	private String etat;
	private Integer payee;
	private Set cltProdGarVends = new HashSet(0);

	public Reparations() {
	}

	public Reparations(int idReparation, Reparateurs reparateurs) {
		this.idReparation = idReparation;
		this.reparateurs = reparateurs;
	}

	public Reparations(int idReparation, Pannes pannes,
			Reparateurs reparateurs, String description, Date dateEtat,
			String etat, Integer payee, Set cltProdGarVends) {
		this.idReparation = idReparation;
		this.pannes = pannes;
		this.reparateurs = reparateurs;
		this.description = description;
		this.dateEtat = dateEtat;
		this.etat = etat;
		this.payee = payee;
		this.cltProdGarVends = cltProdGarVends;
	}

	@Id
	@Column(name = "id_reparation", unique = true, nullable = false)
	public int getIdReparation() {
		return this.idReparation;
	}

	public void setIdReparation(int idReparation) {
		this.idReparation = idReparation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_panne")
	public Pannes getPannes() {
		return this.pannes;
	}

	public void setPannes(Pannes pannes) {
		this.pannes = pannes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reparateur", nullable = false)
	public Reparateurs getReparateurs() {
		return this.reparateurs;
	}

	public void setReparateurs(Reparateurs reparateurs) {
		this.reparateurs = reparateurs;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_etat", length = 19)
	public Date getDateEtat() {
		return this.dateEtat;
	}

	public void setDateEtat(Date dateEtat) {
		this.dateEtat = dateEtat;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "payee")
	public Integer getPayee() {
		return this.payee;
	}

	public void setPayee(Integer payee) {
		this.payee = payee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reparations")
	public Set getCltProdGarVends() {
		return this.cltProdGarVends;
	}

	public void setCltProdGarVends(Set cltProdGarVends) {
		this.cltProdGarVends = cltProdGarVends;
	}

}
