package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendGarId generated by hbm2java
 */
@Embeddable
public class VendGarId implements java.io.Serializable {

	private int idVendeur;
	private int idGarantie;

	public VendGarId() {
	}

	public VendGarId(int idVendeur, int idGarantie) {
		this.idVendeur = idVendeur;
		this.idGarantie = idGarantie;
	}

	@Column(name = "id_vendeur", nullable = false)
	public int getIdVendeur() {
		return this.idVendeur;
	}

	public void setIdVendeur(int idVendeur) {
		this.idVendeur = idVendeur;
	}

	@Column(name = "id_garantie", nullable = false)
	public int getIdGarantie() {
		return this.idGarantie;
	}

	public void setIdGarantie(int idGarantie) {
		this.idGarantie = idGarantie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendGarId))
			return false;
		VendGarId castOther = (VendGarId) other;

		return (this.getIdVendeur() == castOther.getIdVendeur())
				&& (this.getIdGarantie() == castOther.getIdGarantie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVendeur();
		result = 37 * result + this.getIdGarantie();
		return result;
	}

}
