package fr.adaming.models;

// Generated 18 mai 2015 13:37:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendGar generated by hbm2java
 */
@Entity
@Table(name = "vend_gar", catalog = "dbprojet")
public class VendGar implements java.io.Serializable {

	private VendGarId id;
	private Vendeurs vendeurs;
	private Garanties garanties;

	public VendGar() {
	}

	public VendGar(VendGarId id, Vendeurs vendeurs, Garanties garanties) {
		this.id = id;
		this.vendeurs = vendeurs;
		this.garanties = garanties;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idVendeur", column = @Column(name = "id_vendeur", nullable = false)),
			@AttributeOverride(name = "idGarantie", column = @Column(name = "id_garantie", nullable = false)) })
	public VendGarId getId() {
		return this.id;
	}

	public void setId(VendGarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_vendeur", nullable = false, insertable = false, updatable = false)
	public Vendeurs getVendeurs() {
		return this.vendeurs;
	}

	public void setVendeurs(Vendeurs vendeurs) {
		this.vendeurs = vendeurs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_garantie", nullable = false, insertable = false, updatable = false)
	public Garanties getGaranties() {
		return this.garanties;
	}

	public void setGaranties(Garanties garanties) {
		this.garanties = garanties;
	}

}
